export { Navbar } from './nav/Navbar'
export { Features } from './features/Features'
export { Footer } from './footer/Footer'
export { Hero } from './hero/Hero'
export { Contact } from './contact/Contact'
export { Services } from './services/Services'